### ISSUE TITLE
Firefox Play button broken

### ISSUE THREAD

**Issue by 1000i100** [ncase/simulating#10]
Hi, when i try this simulation in firefox, step button work, but play/pause switch visualy but nothing happen on the tree/fire playground.
In console, i only have a warning about scrolling : 
`Ce site semble utiliser un effet de positionnement lié au défilement. Cet effet pourrait ne pas fonctionner correctement avec le défilement asynchrone. Consultez https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects pour obtenir davantage de détails ou discuter des outils et des fonctionnalités liés.`
no error.

I've tested it in chrome, it work fine.

**Comment by wizzwizz4** [comment]
Which version of Firefox? You can find out from About Firefox in the = menu.

**Comment by 1000i100** [comment]
version 61.0.1 (64-bit) on Linux Elementary OS (but last test was in windows 10 probably with the same firefox version or 62 version.

it fail on http://ncase.me/simulating/model/
but not on http://ncase.me/simulating/

**Comment by wizzwizz4** [comment]
I'm on 62.0 on Debian and both work fine. Are you sure you're not using NoScript or something to block it?

**Comment by 1000i100** [comment]
I don't have NoScript or js blocker but uBlock, privacyBadger... but you have no tracker so everything is fine...

But I also use Wappalyzer 5.5.3, and strangly, disabling it let the simulation work fine...

I will send them a report about that.
